spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:clubhouse
    username: sa
    password: 1234

  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
