spring:
  profiles:
    group:
      local:
        - jwt
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/clubhouse
    username: sa
    password:

  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
#    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    import: application-key.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#
#logging:
#  level:
#    org:
#      springframework: DEBUG


