spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:clubhouse
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secretKey: 1111111111111111
  access:
    expiration: 100000

  refresh:
    expiration: 1000000